### ISSUE TITLE
Add "events" documentation

### ISSUE THREAD

**Issue by phisad** [clp-research/slurk#109]
The documentation on emitted events is a bit sparse. In particular, it is very unclear when on_status, joined_room and new_room is emitted (if at all). Furthermore, there are events intended for the server and ones for the client which differ only in word order e.g. "class_add" vs. "add_class".

We should have an overview page with each event and its data structure and the circumenstances when it is triggered.

This is what I could summarize so far:

# Slurk listens to

## Events sent by layouts

- keypress
    - emits start_typing or stop_typing     for each current_user room
    
- typed_message
    - emits user_message for each current_user room
    
- text
    - emits text_message for the room where the user typed (contained in the payload)
    - emits stop_typing  for each current_user room
    
- message_command
    - emits command      for the room where the user typed (contained in the payload)
    - emits stop_typing  for each current_user room

- image
    - emits image_message   for the room where the user typed (contained in the payload)
    - emits stop_typing     for each current_user room

## Events sent by bots programmatically via programmer

- set_attribute
    - emits attribute_update  for the room
    
- set_text
    - emits text_update       for the room
    
- add_class
    - emits class_add         for the room
    
- remove_class
    - emits class_removed     for the room

- room_created
    - emits new_room          for everyone (broadcast)
    - emits new_task_room     for everyone (broadcast) if task in data
    
- join_room (might also be emitted by the layout)
    - emits joined_room       for the room

- leave_room (might also be emitted by the layout)
    - emits left_room         for the room

## Events sent by bots automatically via socketio framework

- connect
    - emits status      for each current_user room
- disconnect
    - emits status      for each current_user room
    - emits left_room   for each current_user room
- ready
    - emits joined_room for each current_user room
    
## Events sent by socketio

- log
    - emits nothing

## Notes

- the intended receiver for most of the events is the javascript client manipulating the layout

- bots might listen to:
    - new_room      (possibly as a callback to a rest api call)
    - new_task_room (possibly as a callback to a rest api call)
    - status
    - left_room     (possibly to catch user logouts)
    - joined_room   (possibly to catch new user logins)
    - user_message
    - text_message
    - command

- there are special messages:
    - starting "@<user>"                    for private messages to user
    - starting "/"                          for commands
    - starting "image:<image-url>"          for image messages
    - starting "@<user> image:<image-url>"  for private image message

**Comment by TimDiekmann** [comment]
Closing in favor of #153
