### ISSUE TITLE
Usage of marshmellow? 

### ISSUE THREAD

**Issue by TimDiekmann** [clp-research/slurk#113]
Do we want to add [marshmallow](https://marshmallow.readthedocs.io/en/stable/) as dependency? It simplifies generating the REST API. But it also introduces another dependency.

**Comment by phisad** [comment]
Could you show a before and after example for a specific use case in the slurk api?

**Comment by TimDiekmann** [comment]
Sure!

**Comment by TimDiekmann** [comment]
it basically boils down to this:

```python
class TokenSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Token
        include_relationships = True
        include_fk = True
        load_instance = True

@api.route('/token/<string:id>', methods=['GET'])
@auth.login_required
def get_token(id):
    if not g.current_permissions.token_query and not (g.current_user and str(g.current_user.token) == id):
        abort(Forbidden)

    db = current_app.session
    schema = TokenSchema()

    token = db.query(Token).get(id)
    if token:
        return make_response(schema.dump(token))
    else:
        return make_response(jsonify({'error': 'token not found'}), 404)


@api.route('/token', methods=['POST'])
@auth.login_required
def post_token():
    if not g.current_permissions.token_generate:
        abort(Forbidden)

    data = get_json(request)

    db = current_app.session

    permissions_id = # ... TODO: Add and use PermissionsSchema
    data['permissions_id'] = permissions.id

    schema = TokenSchema(session=db)

    validation = schema.validate(data)
    if validation != {}:
        abort(BadRequest(str(validation)))
        
    token = schema.load(data)
    db.add(token)
    db.commit()

    return make_response(schema.dump(token))
```

The classes are provided in [`marshmallow-sqlalchemy`](https://pypi.org/project/marshmallow-sqlalchemy/).

**Comment by TimDiekmann** [comment]
> The validation logic has been moved to the database constraints

Yes, and that's a pretty big deal IMO as we don't have to verify the data ourselves. Actually, we don't really verify the data currently passed or give the user feedback on what arguments are unused. With marshmallow this is implicit.

> I assume the Token model is otherwise "kind of" untouched in models?

Yes, only a `Schema` for needed for every `Model` class. I think it's also possible to inherit from a parent `Meta` class to avoid code duplication. However, I don't know if everything is possible to implement so easily as I never used the library before. 

> Where exactly is the "simplification" using this lib in our case?

We can get rid of the `as_dict` method on every `Model` class. This implies, that we don't have to remember to add every single field if the database layout changes. It also makes testing easier, because if the layout changes, the tests for the REST API are very likely to fail.

> The schema seems not to do much more than JSON does for us now?

The `Schema` returns a dictionary, which Flask can implicitly convert to JSON when making a `Response` object. It basically replaces `as_dict`, which is currently reading all the values by hand and returning a dictionary.

> The Token fields should go into the schema then I guess?

The code above is a working example when leaving out the `Permissions`. The `Schema` is defined alongside the `Model` and the `Model` shouldn't need any adjustments I think. It's acting as a (De-)Serializer for the `Model` class.

**Comment by TimDiekmann** [comment]
> In the end, this lib might be a bit overkill for our needs (as it only handles the serialization part and we only use JSON anyway), but still

Marshmallow focuses on Serialization: "marshmallow: simplified object serialization":
> marshmallow is an ORM/ODM/framework-agnostic library for converting complex datatypes, such as objects, to and from native Python datatypes.

> `include_relationship=True`

The user don't need to care, how exactly the model is implemented. Acting with relationships is easier in most cases.

**Comment by phisad** [comment]
> The user don't need to care, how exactly the model is implemented

The "user" is us and we need to know. ;-) But yeah, if `as_dict` is such a burden and we have better test-ability, then why not.
