### ISSUE TITLE
RFC: Remove `Permissions`

### ISSUE THREAD

**Issue by TimDiekmann** [clp-research/slurk#118]
The `Permissions` entries are rather big and with more features the bigger it gets. My suggestion is to get rid of `Permissions` and check if the `Token` has a room associated. If so, it is not allowed to be used in the REST API (besides query information the user requires like the room layout). If no room is set, the token is an API token, which can use the whole REST API.

**Comment by janagoetze** [comment]
you mean get rid of this class/table? https://github.com/clp-research/slurk/blob/development/app/models/permission.py

**Comment by TimDiekmann** [comment]
Yes!

**Comment by TimDiekmann** [comment]
In today's meeting we decided to reduce the `Permissions` table to the minimum, i.e. remove all the API stuff but keep the Socketio stuff.
