### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by TimDiekmann** [clp-research/slurk#139]
Travis is not authorized to build anymore:
```
Could not authorize build request for clp-research/slurk.
```

Probably, the `GH_TOKEN` by @davidschlangen is not valid anymore. Either, we need a new token or we may switch to GitHub Actions instead.

**Comment by davidschlangen** [comment]
I need more information. What do I need to do precisely?

**Comment by TimDiekmann** [comment]
Travis needs to be authorized to test the builds, we had that set up together at the time. Recently this no longer works. I.e. tests are no longer executed on pull requests and no documentation is created on push to the master branch. 
So Travis has to be reauthorized or we switch directly to GitHub Actions, then we don't have to rely on Travis. 
We can also do this on occasion via Zoom and Screen Sharing if there is a problem with authorization.
