### ISSUE TITLE
500 Status Code for Layout Deletion

### ISSUE THREAD

**Issue by wencke-lm** [clp-research/slurk#143]
Deleting a Layout fails with a 500 status code if the layout is used in a room.

I think in an older slurk version it was possible to set the layout of a room to null. And if this was the case the default.json layout was used.

<img width="455" alt="status_code" src="https://user-images.githubusercontent.com/66587202/123550481-f4004e80-d76d-11eb-8e1b-d1f2d1a2d387.png">
<img width="635" alt="error" src="https://user-images.githubusercontent.com/66587202/123550483-f5ca1200-d76d-11eb-9887-b774989b89c1.png">

@TimDiekmann

**Comment by wencke-lm** [comment]
That's not a problem pertinent to the Layout table alone. Same applies to deleting permissions while they are used in a token.

**Comment by TimDiekmann** [comment]
As I'd avoid cascading deletion in slurk this error should be caught and return a 409 error code (conflict).
