### ISSUE TITLE
Permissions attribute `private_message` missing

### ISSUE THREAD

**Issue by wencke-lm** [clp-research/slurk#178]
But its existence is assumed in `slurk/views/chat/events.py`, which currently causes an error for privately sent messages.
Not sure whether:
1. Now everyone that can send messages should be allowed to also send private messages
2. only api tokens should be allowed to send private messages
3. we add the attribute again so that it can be adjusted separately for each token

<img width="660" alt="send_private_message_error" src="https://user-images.githubusercontent.com/66587202/126079563-02e1f364-3c07-4ec2-9025-c4b0b3fff905.png">

**Comment by TimDiekmann** [comment]
As in #181 I'd use the third option.
