### ISSUE TITLE
`joined_room` event late?

### ISSUE THREAD

**Issue by wencke-lm** [clp-research/slurk#180]
The `joined_room` event triggeres a function on the javascript side that applies the layout, which includes registering scripts.
It is (theoretically) sent before any `status` event.

<img width="554" alt="code" src="https://user-images.githubusercontent.com/66587202/126220910-f0d422a0-b3de-4d6e-96b3-51c96dad3999.png">

The concierge bot used to receive the `status:join` event and greet the joined user immediately. In order for the user to receive this message (it to be shown to him) the registration of scripts must have been completed. This does not seem to be the case:

<img width="563" alt="problem" src="https://user-images.githubusercontent.com/66587202/126221402-fd96f4b2-6f34-48e4-9c7c-aa8857c843d0.png">

The problem is solved by adding a time.sleep(2) between the point in time that the concierge bot receives the `status` event and the time it sends the message. But this is not a good solution and definitely no general solution in my opinion.

**Comment by TimDiekmann** [comment]
This is, why I previously introduced the `ready` event, but then some messages may be ignored. I'd add an event queue, where incoming events will be pushed into as long as `joined_room` was not called. After `joined_room`, the event queue could then be used to simulate past events.
