### ISSUE TITLE
make chat area / display area ratio changeable at startup

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#249]
In the current version of slurk, it is possible to drag the divider between the chat area and the display area to change their relative sizes. Apparently it is not possible to make it so that when a user enters a task room, this ratio is automatically set. 

It would be good if that were possible. (The chat area doesn't really need a lot of horizontal space, but sometimes the display area does. It would be good if that could be achieved without having to tell the user that they need to do something, like dragging the divider, manually.)

**Comment by sebag90** [comment]
This issue was addressed [in this pull request](https://github.com/clp-research/slurk-bots/pull/55).
Each bot that inherits from the abstract class can now resize the chat and task area based on percentage values.
