### ISSUE TITLE
create docker file that encapsulates deployment

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#31]
one docker file that starts nginx, gunicorn, slurk...

derive from that docker container that also starts bot.

Advantage: test deployment environment on your own machine.

**Comment by TimDiekmann** [comment]
Pushing the priority as this will be very helpful for moving to Potsdam.

**Comment by TimDiekmann** [comment]
@nilinykh I may need your help there, I'd come back to you then.

**Comment by TimDiekmann** [comment]
The docker images will be created by `docker-compose`. Thus the _config.ini_ has to be provided. Any idea how to configure the server then? Maybe support command line arguments along to the config file, which would overwrite the config?
