### ISSUE TITLE
Standard format for task repositories

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#45]
Repos for bots (= one experiment) should follow same format. Maybe integrate slurk as git submodule.

**Comment by TimDiekmann** [comment]
cc #38

**Comment by TimDiekmann** [comment]
cc #38 

@nattari @simeonschuez @nilinykh We should work out, how a standard format for a task repository should look like.

**Comment by TimDiekmann** [comment]
I'd like to postpone this until #51 has landed as I think Docker will have a great impact on a task repository.

**Comment by TimDiekmann** [comment]
@simeonschuez and I worked out a structure. There should be a template bot repository (@davidschlangen maybe dsg-bielefeld/slurk-bot-template?). For writing bots, this repo can then be forked and consists of
   - bot
   - layouts
   - plugins
   - data (arbitrary)
   - Dockerfile template (use env to pass arguments)
   - (startup script which generates token for bot, similar to the one in *tools/*)
   - (default config.ini?)

CC @nattari @nilinykh, you may want to add your thoughts on this?
