### ISSUE TITLE
change of organisation name imminent

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#66]
With the move of the lab, the name of the organisation will have to change as well. Which means that the URLs change. My understanding is that at least for a while, github will automatically forward requests to the old URL.

But still, things that are under our control should be adapted, if and where we see them. That is, should there be any absolute links in the documentation, they will need to be adapted. (Ideally, to relative URLs, otherwise to contain the new organisation name, once I know it.)

**Comment by TimDiekmann** [comment]
Absolute links is currently only used here:
https://github.com/dsg-bielefeld/slurk/blob/f897c3582d5d534c83131ad72f5b49507f17450d/README.md#L20-L22
