### ISSUE TITLE
create parallel repo for bots / experiments?

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#72]
So maybe this is the best solution: We create another repository, let say `slurk-bots`, in which we collect all bots that we have created so far (beyond the pairup and minimal bot, which should stay here). These bots should live in a separate directories and be self-contained, and ideally be abstracted away a bit from any specific data that was used for specific experiments with them.

Off the top of my head, I can think of: the meetup bot ( @nilinykh ), the matchup bot ( @nilinykh ), the agreement game bot (@nattari , @atuefekci ), the mouse tracking bot / layout ( @simeonschuez ) , the viewport / zooming on images bot / layout ( @simeonschuez ). These should all be collected here.

**Comment by davidschlangen** [comment]
Documenting Simeon's reply here:
> die Slurk-Sachen heraus zu suchen, die ich in Bielefeld erstellt habe. Die sind in meinem Fork von Slurk. Die relevanten Dateien müssten unter sample_bots, unter app/static/layouts und unter app/static/plugins liegen.
> Hier die Links:
> Die Zoom-Funktion für Bilder: https://github.com/simeonschuez/slurk/tree/image-zoom
> Die Mouse-Tracking-Geschichte: https://github.com/simeonschuez/slurk/tree/imageclick_currentslurk
> Zu letzterem gehören noch einige Skripte und Notebooks, die hier liegen: https://github.com/simeonschuez/mouse-tracking-experiment

**Comment by janagoetze** [comment]
done
