### ISSUE TITLE
Add example to QuickStart of how to get at logs

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/slurk#75]
The title already is says it. The main purpose of this tool is to enable data collections, so the documentation should talk more about the logs — how to get them, and how to process them. Starting from the QuickStart page.

**Comment by TimDiekmann** [comment]
Added in ced0add00b2c66cef03751efc27e88b9e4d9e78e: https://clp-research.github.io/slurk/slurk_gettingstarted.html#examining-the-log-files
